apiVersion: v1
kind: Namespace
metadata:
  name: sportapps-ns

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: sportapps-service-account
  namespace: sportapps-ns
  annotations:
    iam.gke.io/gcp-service-account: sportsappserviceaccount@sportsapp-365801.iam.gserviceaccount.com

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-be-role
  namespace: sportapps-ns
rules:
  - apiGroups: ["*"]
    resources: ["services"]
    verbs: ["get", "list"]
  - apiGroups: ["*"]
    resources: ["secrets"]
    verbs: ["get"]
  - apiGroups: ["*"]
    resources: ["configmaps"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["services", "endpoints", "pods"]
    verbs: ["get", "list"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-be-role-binding
  namespace: sportapps-ns
subjects:
  - kind: ServiceAccount
    name: sportapps-service-account
    namespace: sportapps-ns
    apiGroup: ""
  - kind: User
    name: system:serviceaccount:sportapps-ns:default
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-be-role
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sportapps-ingress
  namespace: sportapps-ns
  labels:
    app: sportapps-ingress
spec:
  rules:
    - http:
        paths:
          - path: /front
            pathType: Prefix
            backend:
              service:
                name: front
                port:
                  number: 80
          - path: /back
            pathType: Prefix
            backend:
              service:
                name: user
                port:
                  number: 3000