apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
  namespace: sportapps-ns
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      serviceAccountName: sportapps-service-account
      automountServiceAccountToken: true    
      containers:
        - name: user
          image: us-central1-docker.pkg.dev/sportsapp-365801/users-sportsapp/user-image:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 0.7Gi
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: port
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: name
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: username     
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: users-secret
                  key: db_password
                  optional: false
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: users-secret
                  key: jwt_secret
                  optional: false
      tolerations:
      - key: instance_type
        value: spot
        effect: NoSchedule
        operator: Equal
