apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  namespace: sportapps-ns
  labels:
    app: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
        image: us-central1-docker.pkg.dev/sportsapp-365801/front-sportsapp/front:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 0.7Gi
      tolerations:
      - key: instance_type
        value: spot
        effect: NoSchedule
        operator: Equal