apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: users-hpa
  namespace: sportapps-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: users
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
     name: cpu
     target:
       type: Utilization
       averageUtilization: 60
  - type: Resource
    resource:
     name: memory
     target:
       type: Utilization
       averageValue: 800Mi