apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-front
  labels:
    app: angular-front
spec:
  replicas: 1
  selector:
    matchLabels:
        app: angular-front
  template:
    metadata:
      labels:
        app: angular-front
    spec:
      containers:
        - name: angular-front
          image: LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: angular-front
  name: angular-front
spec:
  type: LoadBalancer
  ports:
    - name: angular-front
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: angular-front
