apiVersion: v1
kind: Service
metadata:
  name: users
  namespace: sportapps-ns
  labels:
    app: users
spec:
  type: ClusterIP
  selector:
    app: users
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP