apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: sportapps-ns
  labels:
    app: user
spec:
  type: ClusterIP
  selector:
    app: user
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: front
  namespace: sportapps-ns
  labels:
    app: front
spec:
  type: ClusterIP
  selector:
    app: front
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP